BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Skills` (
	`Item_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name` TEXT
);
CREATE TABLE IF NOT EXISTS `Combat` (
	`Item_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name` TEXT
);
COMMIT;
